Bidirectional Ring
google/paragraph pull request #20
Opened 2021-02-09 03:47 UTC by michael-isaev

Added translation for AllGather, ReduceScatter, and AllReduce for bi-directional ring topology

2021-02-09 06:04 UTC, nicmcd requested changes

2021-02-09 06:04 UTC, nicmcd commented on paragraph/translation/allgather/bidir_ring_allgather_translator.cc
> +/* Copyright 2020 Google LLC
2021

2021-02-09 06:04 UTC, nicmcd commented on paragraph/translation/allgather/bidir_ring_allgather_translator.cc
> +  nlohmann::json implicit_config = R"(
You only need:
{ "algorithm": "unidir-ring" }

No need to create more then ignore it.

2021-02-09 06:22 UTC, michael-isaev commented on paragraph/translation/allgather/bidir_ring_allgather_translator.cc
> +/* Copyright 2020 Google LLC
time flies...

2021-02-16 23:04 UTC, nicmcd approved these changes

2021-02-17 01:15 UTC, merged